### ISSUE TITLE
Programmatic support for CacheLocators in JBossPDP

### ISSUE THREAD

**Issue by Beeee** [picketbox/security-xacml#8]
I am trying to programmatic add CacheLocators in the JBossPDP class. But it don't seem to be possible because of the limited access-level of the cacheLocators list. 

Such feature would make it possible to have the cacheLocators as spring-beans, and then be able to replace those beans with stubs in the tests etc.

Are there any good reason why this is prohibited? Is it sufficient to add a setter-method for the mentioned list?

**Comment by anilsaldhana** [comment]
The cache locators were supposed to be read from the configuration file just like other things. There was no intention of injection when it was designed.

**Comment by Beeee** [comment]
I see.
The lack of proper dependency injection support for locators and cache locators is creating some nasty workarounds in my current project. I guess the correct label for this issue is "feature request", as it obviously not is a bug.

Thank you for a fast reply to my question.

**Comment by anilsaldhana** [comment]
Have you considered placing a pull request with the changes?

**Comment by Beeee** [comment]
Yes, perhaps i will look into it if i have some spare time.

Im closing this issue.
